plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - Adding_a_New_VMware_vCenter.md
  - Administration_Settings.md
  - Calculation_of_Snapshot_Space.md
  - Changing_the_Default_Dashboard.md
  - Configure_Alerting_or_Notification_Channel_.md
  - Dashboards_History_versioning_.md
  - Dashboards.md
  - Data_Retention.md
  - Deleting_a_vCenter.md
  - Design_your_own_dashboards.md
  - Editing_a_vCenter.md
  - Export_and_Import_Dashboards.md
  - FAQ.md
  - Getting_Started.md
  - index.md
  - Installing_the_Virtual_Appliance.md
  - Integration_Cisco_UCS.md
  - Integration_DataCore_SANSymphony.md
  - Integration_Kubernetes.md
  - Integration_Linux.md
  - Integration_Microsoft_SQL_Server_agentless_.md
  - Integration_Microsoft_Windows_Hyper-V.md
  - Integration_Microsoft_Windows.md
  - Integration_NetApp_Filer.md
  - Integration_NetApp_Solidfire.md
  - Integration_Nutanix_Prism_Central.md
  - Integration_Oracle_Database.md
  - Integration_Veeam_Backup_Enterprise_Manager.md
  - Integration_VMware_Horizon_View.md
  - Logging_into_Performance_Analyzer.md
  - Mail_Settings.md
  - Maintaining_Time.md
  - Monitoring_Snapshots.md
  - Multi-Tenant_Environments.md
  - Navigating_Performance_Analyzer.md
  - Overview.md
  - Performance_Analyzer_First_Steps.md
  - Playlists.md
  - Reports.md
  - Share_a_Dashboard_Link.md
  - Snapshots.md
  - SSL_Details_CSR_generation_.md
  - Testing_a_vCenter.md
  - Using_Dashboards.md
  - Using_opvizor_PerfAnalyzer.md
  - VMware_vCenter.md
  - vscsiStats.md
